#!/usr/bin/env bash
# Script to transfer a file from our client to a server

# Check if less than 4 parameters were passed
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign input parameters to variables
FILE=$1
IP=$2
USERNAME=$3
SSH_KEY=$4

# Use scp to transfer the file
scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE" "${USERNAME}@${IP}:~/"
