#!/usr/bin/env bash
# Script to install and configure nginx

# Update the package lists for upgrades and new package installations
sudo apt-get update -y

# Install nginx
sudo apt-get install -y nginx

ufw allow 'Nginx HTTP'
# Create a new index.html file
echo "Hello World!" > /var/www/html/index.html


# Restart nginx
sudo service nginx start
