#!/usr/bin/env bash
#!/bin/bash
# Script to install and configure nginx

# Update the package lists for upgrades and new package installations
sudo apt-get update -y

# Install nginx
sudo apt-get install -y nginx

# Start nginx
sudo service nginx start

# Create a new index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Replace the default nginx configuration file to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default
sudo sed -i 's/listen [::]:80 default_server;/listen [::]:8080 default_server;/g' /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart
