#!/usr/bin/env bash
# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
echo "
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
" | sudo tee /etc/haproxy/haproxy.cfg

# Restart HAProxy to apply the changes
sudo systemctl restart haproxy