#!/usr/bin/env bash
# Install Nginx
service nginx start
echo "server { listen 80; }" > /etc/nginx/sites-available/default
echo "server { listen 80; }" > /etc/nginx/sites-enabled/default
service nginx restart
