#!/usr/bin/env bash
# until-count: display a series of numbers
for num in {1..100}
do
	if (( num % 3 == 0 || num % 5 == 0 ))
	then
		if (( num % 3 == 0 && num % 5 == 0 ))
		then
			echo "FizzBuzz"
		elif (( num % 3 == 0 ))
		then
			echo "Fizz"
		else
			echo "Buzz"
		fi
	else
		echo "$num"
	fi
done
