#!/usr/bin/env bash
# until-count: display a series of numbers
IFS=':'
while read line
do
    read -ra arr <<< "${line}"
    echo "The user ${arr[0]} is part of the ${arr[3]} gang, lives in ${arr[5]} and rides ${arr[6]}. ${arr[2]} place is protected by the passcode ${arr[1]}, more info about the user here: ${arr[4]}"
done < /etc/passwd
