#!/usr/bin/env bash
# while-count: display a series of numbers
# 9th time print Hi
count=1
while [ $count -le 10 ];
do
	if [ $count -eq 9 ]
		then echo "Hi"
	else
		echo "Best School"
	fi
count=$(( count + 1 ))
done
