#!/usr/bin/env bash
# while-count: display a series of numbers
# 9th time print Hi
count=0
while [ $count -le 9 ];
do
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	count=$(( count + 1 ))
done
