#!/usr/bin/env bash
# while-count: display a series of numbers
# 9th time print Hi
count=1
while [ $count -le 10 ];
do
	if [ $count -eq 4 ]
	then
		echo "bad luck"
	elif [ $count -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	count=$(( count + 1 ))
done
