#!/usr/bin/env bash
#script that configures an Ubuntu server
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8
cp /etc/hosts ~/hosts.new
echo "localhost	127.0.0.2" > ~/hosts.new
echo "facebook.com	8.8.8.8" >> ~/hosts.new
cat ~/hosts.new > /etc/hosts
